parameters:
  mc.private.content.sites_extensions.class: MC\Bundle\PrivateContentAccessBundle\Custom\PrivateContentTab
  mc.pre_content_view_listener.class: MC\Bundle\PrivateContentAccessBundle\Listener\PreContentViewListener


services:
  mc.private.content.sites_extensions:
    class: "%mc.private.content.sites_extensions.class%"
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - { name: ezplatform.tab, group: location-view }

  mc_privateaccess.controller.form:
    public: true
    class: MC\Bundle\PrivateContentAccessBundle\Controller\PrivateAccessController
    arguments:
      - '@templating'
      - '@ezpublish.api.service.search'
      - '@ezpublish.api.service.content'
      - '$languages$'

  private_access_form.types.custom_form:
    class: MC\Bundle\PrivateContentAccessBundle\Form
    tags:
      - { name: form.type, alias: 'private_access_form' }
    arguments:
      - "@ezpublish.api.service.location"

  mc.pre_content_view_listener:
    class: '%mc.pre_content_view_listener.class%'
    tags:
      - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}
    arguments:
      - '@eZ\Publish\API\Repository\PermissionResolver'
      - '@ezpublish.api.repository'
      - '@eZ\Publish\API\Repository\ContentService'
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@session'
