parameters:
    novactive.novaseobundle.application_config.provider.admin_ui.seo_metas.class: Novactive\Bundle\eZSEOBundle\ApplicationConfig\Providers\AdminUI\SeoMetas

services:
    novactive.novaseobundle.application_config.provider.admin_ui.seo_metas:
      class: "%novactive.novaseobundle.application_config.provider.admin_ui.seo_metas.class%"
      arguments:
          - "@ezpublish.config.resolver"
      tags:
          - { name: ezplatform.admin_ui.config_provider, key: 'seoMetas' }

    ezplatform.adminui.novaseobundle.css:
        parent: EzSystems\EzPlatformAdminUi\Component\LinkComponent
        arguments:
            $href: "/bundles/novaezseo/css/views/fields/edit/novaseometas.css"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    ezplatform.adminui.novaseobundle.css_font:
        parent: EzSystems\EzPlatformAdminUi\Component\LinkComponent
        arguments:
            $href: "/bundles/novaezseo/font/font-awesome.min.css"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
