parameters:
    novae_zseo.default.robots_disallow: ~
    novae_zseo.default.google_verification: ~
    novae_zseo.default.fieldtype_metas_identifier: "metas"
    novae_zseo.default.fieldtype_metas:
        title:
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'book'
        description:
            label: 'Description'
            default_pattern: ~
            icon: 'book'
        keyword:
            label: 'Keywords'
            default_pattern: ~
            icon: 'tags'
        'og:title':
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'facebook-official'
        'og:description':
            label: 'Descrition'
            default_pattern: "<short_descrition|description|title|name>"
            icon: 'facebook-official'
        'og:image':
            label: 'Image'
            default_pattern: "<image|picture>"
            icon: 'facebook-official'
        'twitter:title':
            label: 'Title'
            default_pattern: "<title|name>"
            icon: 'twitter-square'
        'twitter:description':
            label: 'Descrition'
            default_pattern: "<short_descrition|description|title|name>"
            icon: 'twitter-square'
        'twitter:image':
            label: 'Image'
            default_pattern: "<image|picture>"
            icon: 'twitter-square'