parameters:
    novactive.novaseobundle.legacy.configuration.class: Novactive\Bundle\eZSEOBundle\Core\LegacyConfiguration
services:
    novactive.novaseobundle.legacy.configuration:
        class: %novactive.novaseobundle.legacy.configuration.class%
        arguments:
            - @ezpublish.config.resolver.core
        tags:
            - { name: kernel.event_subscriber }