name: app
type: php:7.2
build:
    flavor: "none"

relationships:
    database: 'mysqldb:user'
variables:
    env:
        SYMFONY_ENV: dev
web:
    locations:
        "/":
            root: "ezplatform/web"
            passthru: "/app.php"
            expires: 600
disk: 2048
mounts:
    "/ezplatform/var/cache": "local:files/cache"
    "/ezplatform/var/logs": "local:files/logs"
    "/ezplatform/web/var": "shared:files/files"
    "/ezplatform/var/sessions": "shared:files/sessions"
hooks:
    build: |
        set -e
        composer create-project ezsystems/ezplatform --prefer-dist --no-progress --no-interaction
        cd ezplatform
        composer require nesbot/carbon gedmo/doctrine-extensions doctrine/doctrine-fixtures-bundle fzaninotto/faker
        cd ..
        rm ezplatform/web/app_dev.php
        mv tests/platform.sh/AppKernel.php ezplatform/app/AppKernel.php
        cat tests/platform.sh/configs.yaml >> ezplatform/app/config/config.yml
        cat tests/platform.sh/routes.yaml >> ezplatform/app/config/routing.yml
        mkdir -p ezplatform/src/Novactive/Bundle
        mv bundle ezplatform/src/Novactive/Bundle/eZMailingBundle
        # cheat the autoloader - we should be able to do better
        mv ezplatform/vendor/autoload.php ezplatform/vendor/autoload_orig.php
        mv tests/platform.sh/autoload.php ezplatform/vendor/autoload.php
        cd ezplatform
        bin/console assets:install

    deploy: |
        set -e
        cd ezplatform
        bin/console ezplatform:install clean
        bin/console novaezmailing:install
        bin/console doctrine:fixtures:load --no-interaction
        mv var/cache/$SYMFONY_ENV var/cache/oldcache
        bin/console cache:clear
    post_deploy: |
        set -e
        find var/cache/$SYMFONY_ENV -mindepth 1 -maxdepth 1 -type d \! \( -name "$PLATFORM_TREE_ID" \) -exec rm -rf '{}' \;

runtime:
    extensions:
        - xsl
        - imagick
        - readline
