language: php
dist: xenial
php:
    - '7.2'

before_install:
    - phpenv config-rm xdebug.ini

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry

script:
    - ./vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php bundle tests
    - ./vendor/bin/phpmd bundle,tests text .cs/md_ruleset.xml


notifications:
    email: false
