dist: trusty
sudo: false
language: php
php:
  - '7.1'

services:
  - docker

before_install:
  # execute all of the commands which need to be executed before installing dependencies
  - docker pull postman/newman_ubuntu1404:latest

install:
  # install all of the dependencies you need here

before_script:
  # execute all of the commands which need to be executed before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - docker run --net=host -v $(pwd)/wwwroot/tests/postman:/etc/newman -t postman/newman_ubuntu1404 run collection.json --environment environment.json

#after_success:

#after_failure:

notifications:
  email: false
