services:
    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\EnhancedImageStorage:
        parent: Ibexa\Core\FieldType\Image\ImageStorage
        tags:
            - {name: ibexa.field_type.external_storage_handler, alias: enhancedimage}

    ibexa.field_type.indexable.enhancedimage:
        parent: Ibexa\Core\FieldType\Image\SearchField
        class: Ibexa\Core\FieldType\Image\SearchField
        tags:
            - {name: ibexa.field_type.indexable, alias: enhancedimage}

    ibexa_rest.field_type_processor.enhancedimage:
        parent: Ibexa\Rest\FieldTypeProcessor\ImageProcessor
        tags:
            - { name: ibexa.rest.field_type.processor, alias: enhancedimage }

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\Type:
        parent: Ibexa\Core\FieldType\Image\Type
        tags:
            - {name: ibexa.field_type, alias: enhancedimage}

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\ValueConverter:
        parent: Ibexa\Core\Persistence\Legacy\Content\FieldValue\Converter\ImageConverter
        tags:
            - {name: ibexa.field_type.legacy_storage.converter, alias: enhancedimage}

    Novactive\EzEnhancedImageAsset\FieldType\EnhancedImage\FormMapper:
        autoconfigure: true
        autowire: true
        tags:
            - { name: ibexa.field_type.form_mapper.definition, fieldType: enhancedimage }
            - { name: ibexa.field_type.form_mapper.value, fieldType: enhancedimage }
