services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    nova_ez.ldap.login_listener:
        class: Novactive\EzLdapAuthenticator\EventListener\InteractiveLoginListener
        arguments:
            $ldap: '@Symfony\Component\Ldap\Ldap'

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments: []

    nova_ez.ldap.user.provider:
        class: Symfony\Component\Security\Core\User\LdapUserProvider
        arguments: []