services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    nova_ez.ldap.login_listener:
        class: Novactive\EzLdapAuthenticator\EventListener\InteractiveLoginListener
        arguments:
            $ldap: '@Symfony\Component\Ldap\Ldap'
            $config: '%nova_ez_ldap%'

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -
                connection_string: 'ldap://ldap'
                version: 3