services:

    # FIELD TYPE
    Novactive\Bundle\eZSEOBundle\Core\FieldType\Metas\Type:
        parent: ezpublish.fieldType
        tags:
            - { name: ezpublish.fieldType, alias: novaseometas }

    Novactive\Bundle\eZSEOBundle\Core\SeoMetas:
        arguments:
            - "@ezpublish.config.resolver"
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'seoMetas' }

    ezplatform.adminui.novaseobundle.css:
        parent: EzSystems\EzPlatformAdminUi\Component\LinkComponent
        arguments:
            $href: "/bundles/novaezseo/css/views/fields/edit/novaseometas.css"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    ezplatform.adminui.novaseobundle.css_font:
        parent: EzSystems\EzPlatformAdminUi\Component\LinkComponent
        arguments:
            $href: "/bundles/novaezseo/font/font-awesome.min.css"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
