services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    nova_ez.ldap.login_listener:
        class: Novactive\Bundle\eZLDAPAuthenticatorBundle\Listener\InteractiveLoginListener
        arguments:
            $ldap: '@nova_ez.ldap'
            $config: '%nova_ez_ldap%'
            $translator: '@translator'
            $tokenStorage: '@security.token_storage'

    nova_ez.ldap.adapter:
        class: Novactive\Bundle\eZLDAPAuthenticatorBundle\Adapter\NovaEzLdapAdapter
        arguments: ['%nova_ez_ldap%']

    nova_ez.ldap.user_provider:
        class: Novactive\Bundle\eZLDAPAuthenticatorBundle\User\NovaEzLdapUserProvider
        arguments:
            $ldap: '@nova_ez.ldap'
            $config: '%nova_ez_ldap%'

    nova_ez.ldap:
        class: Symfony\Component\Ldap\Ldap
        arguments: ['@nova_ez.ldap.adapter']
